#!/usr/bin/env bash
# Align reads to IMG
# Input directory has one FASTA (.fna extension) file per sample
#shogun_bt2_lca -i data/qc_reads -o bt2 -l False -b /project/flatiron2/data/img/annotated/genes_bt2/img.genes

# Input is a folder filled with SAM files, one SAM file per sample
kegg_parse_img_ids -i bt2 -o kegg.csv

# Input file is the KEGG csv file from the kegg_parse_img_ids
# -m mapping file for IMG gene to ko-map was generated by you in the spring
kegg_predictions -i kegg.csv -o kegg_mapping  --algorithm intersection -m /project/flatiron/data/img/img-gene-ko-map.txt
